language: ruby
cache: bundler
sudo: false
rvm:
#  - 2.4.5
#  - 2.5.3
#  - 2.6.0
  - jruby-9.2
  #  - rubinius-3.107
  #  - rubinius-4.2
#  - truffleruby
gemfile:
  - gemfiles/rails_4.2.gemfile
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile
  - gemfiles/sinatra.gemfile
matrix:
  exclude:
    # truffleruby does not seem to work with Rails
    - rvm: truffleruby
      gemfile: gemfiles/rails_4.2.gemfile
    - rvm: truffleruby
      gemfile: gemfiles/rails_5.0.gemfile
    - rvm: truffleruby
      gemfile: gemfiles/rails_5.1.gemfile
    - rvm: truffleruby
      gemfile: gemfiles/rails_5.2.gemfile
before_install:
  # Bundler 2.x is not supported for Rails 4.2
  - ( [[ "$BUNDLE_GEMFILE" =~ rails_4.2.gemfile$ ]] && gem uninstall -ax bundler -v '>= 2'|| true) && gem install bundler -v '< 2' ) || true
  # Bundler 2.x is not supported for JRuby
  - ( [[ $TRAVIS_RUBY_VERSION =~ jruby ]] && ( gem uninstall -ax bundler -v '>= 2' --platform java || true ) && gem install bundler -v '< 2' --platform java ) || true
script:
  - bundle exec rspec
addons:
  code_climate:
    repo_token: e233a382471f480a061ac3098edadbb91cee8129e0938973aeb2aa8d84a0a93b
after_success:
  - bundle exec codeclimate-test-reporter
